### ISSUE TITLE
Switching tab clears all existing simple fog maps

### ISSUE THREAD

**Issue by tomu86** [League-of-Foundry-Developers/simplefog#6] opened 2020-12-11 17:47 UTC
I have an issue where I switch level I lose all the simple fog data for that level.

**Comment by akrigline** [comment] 2020-12-11 17:56
Hey @tomu86 can you provide some more detailed information about your setup?

Foundry Core Version: 
System & Version: 
Simplefog Version Installed: 
Any other modules dealing with the canvas installed? 
Can you repro with no other modules installed?

Some more specific reproduction steps would also be useful for us to investigate.

**Comment by crhampton1** [comment] 2020-12-16 00:56
@tomu86, I have tested Foundry on the latest version and have not had any issues. Please update ticket with the above from @akrigline, and also I will add, any errors in the developers tools when opening or switching scenes. 

Thanks!

**Comment by akrigline** [comment] 2020-12-16 05:24
@tomu86 please try uninstalling and reinstalling simplefog. Ensure you are running version `1.1.15`

**Comment by crhampton1** [comment] 2020-12-19 02:23
Closing due to not hearing back from user. Unable to replicate.

**Closed as completed by crhampton1** 2020-12-19 02:23 UTC
Labels: bug, waiting-for-additional

**Comment by sheathompson** [comment] 2021-12-26 20:46
I am having this same issue, soon I change scenes and come back to that scene with modified fog, the fog layer is all messed up and does not resemble anything I had ever done previously.
